image:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

environment:
  BOOST_ROOT: C:/Libraries/boost_1_67_0
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
      BOOST_LIBRARYDIR: C:/Libraries/boost_1_67_0/lib32-msvc-14.1
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BOOST_LIBRARYDIR: C:/Libraries/boost_1_67_0/lib64-msvc-14.1

configuration:
  - Debug
  - Release

before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build

    cd build

    cmake .. -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%configuration%"

build_script:
- cmake --build .

test_script:
- ctest
