image:
  - Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - platform: x86
      GENERATOR: "Visual Studio 15 2017"
    - platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"

configuration:
  - Debug
  - Release

cache:
  - c:\tools\vcpkg\installed\

install:
  - vcpkg install --triplet "%platform%"-windows boost-test

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%"
    "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

build_script:
  - cmake --build . --config %configuration%

test_script:
  - ctest
