image:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

before_build:
- cmd: >-
    vcpkg install boost:"%platform%"-windows

    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build

    cd build

    cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%configuration%"

build_script:
- cmake --build .

test_script:
- ctest
