image:
  - Visual Studio 2017
 
platform:
  - x64 
 
configuration:
#    - Debug
  - Release

build:
    parallel: true

build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build     
    
    cd build    
    
    cmake .. -G "Visual Studio 15" -DBoost_DEBUG=ON
    
    cmake --build .
    
test_script:
- cmd: ctest

