image: 
  - Visual Studio 2017
  - Visual Studio 2017 Preview

environment:
  matrix:
    - generator: "Visual Studio 15 2017"
    - generator: "Visual Studio 15 2017 Win64"

configuration:
  - Debug
  - Release
    
before_build:
- cmd: >-
    vcpkg install boost

    cd %APPVEYOR_BUILD_FOLDER%
    
    mkdir build         
    
    cd build       
    
    cmake .. -G "%generator%"   

build_script:
- cmd: >-
    cmake --build .
    
test_script:
- cmd: >-
    ctest
