image: 
  - Visual Studio 2017

environment:
  matrix:
    - generator: "Visual Studio 15 2017"
      BOOST_ROOT: C:/Libraries/boost_1_67_0
      BOOST_LIBRARYDIR: C:/Libraries/boost_1_67_0/lib32-msvc-14.1
      PATH: "%BOOST_LIBRARYDIR%;%PATH%"

    - generator: "Visual Studio 15 2017 Win64"
      BOOST_ROOT: C:/Libraries/boost_1_67_0
      BOOST_LIBRARYDIR: C:/Libraries/boost_1_67_0/lib64-msvc-14.1
      PATH: "%BOOST_LIBRARYDIR%;%PATH%"

configuration:
  - Debug
  - Release
    
before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%
    
    mkdir build         
    
    cd build       
    
    cmake .. -G "%generator%"   

build_script:
- cmd: >-
    cmake --build .
    
test_script:
- cmd: >-
    ctest
