image:
  - Visual Studio 2019
  - Visual Studio 2019 Preview

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  GENERATOR_NAME: "Visual Studio 16 2019"
  matrix:
    - platform: x86
      PLATFORM_NAME: "Win32"
    - platform: x64
      PLATFORM_NAME: "x64"

configuration:
  - Debug
  - Release

shallow_clone: true

build:
  verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

install:
  - vcpkg install --triplet "%platform%"-windows
    boost-test

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G "%GENERATOR_NAME%" -A %PLATFORM_NAME%
    "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

build_script:
  - cmake --build . --config %configuration%

test_script:
  - ctest
