image:
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  GENERATOR: "Visual Studio 16 2019"

shallow_clone: true

build:
  verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

install:
  - vcpkg install --triplet "%platform%"-windows
    boost-test

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G "%GENERATOR%" -A %platform%
    "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

build_script:
  - cmake --build . --config %configuration%

test_script:
  - ctest
