image:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

environment:
  matrix:
    - platform: x86
      GENERATOR: "Visual Studio 15 2017"
    - platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"

configuration:
  - Debug
  - Release

before_build:
- cmd: >-
    vcpkg upgrade

    vcpkg install boost-test:"%platform%"-windows

    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build

    cd build

    cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "%GENERATOR%"

build_script:
- cmake --build . --config "%configuration%"

test_script:
- ctest
