dist: trusty
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'   
    packages:
    - g++-7
    - clang-5.0 
    - lldb-5.0 
    - lld-5.0
    - libboost-test-dev

matrix:
  include:
    - os: linux
      env: CXX_COMPILER=g++-7 BUILD_TYPE=Debug
    - os: linux
      env: CXX_COMPILER=g++-7 BUILD_TYPE=Release
    - os: linux
      env: CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug    
    - os: linux
      env: CXX_COMPILER=clang++-5.0 BUILD_TYPE=Release   

install:
  
################################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

################################################################################
# Install the latest CMake
################################################################################
- |
  CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}ll
  cmake --version

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
 
script: 
- |
  make -j2
  ctest
