os: linux
dist: trusty
language: cpp
compiler: gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libboost-test-dev

install:
- wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz
- tar xzvf cmake-3.8.1.tar.gz
- cd cmake-3.8.1/
- ./bootstrap
- make -j10
- sudo make install

before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script: 
- (mkdir build && cd build && cmake .. && make)
- ctest
