dist: trusty
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'   
    packages:
    - g++-7
    - clang-5.0
    - libboost-test-dev

matrix:
  include:
    -os: linux
      compiler: gcc
      env: CXX_COMPILER='g++-7'
    -os: linux
      compiler: clang
      env: CXX_COMPILER='clang++-5.0'    

install:

################################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

################################################################################
# Install the latest CMake
################################################################################
- |
  CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}ll
  cmake --version
 
script: 
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. 
  make
  ctest
