language: cpp
os: linux
dist: xenial
sudo: false

matrix:
  include:
    - env: CXX_COMPILER=clang++-6.0 CXX=g++-8
      addons: { apt: { packages: ["clang-6.0", "g++-8", "libboost-test-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"] } }

    - env: CXX_COMPILER=clang++-7 CXX=g++-8
      addons: { apt: { packages: ["clang-7", "g++-8", "libboost-test-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7"] } }

    - env: CXX_COMPILER=clang++-8 CXX=g++-8
      addons: { apt: { packages: ["clang-8", "g++-8", "libboost-test-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-8"] } }

    - env: CXX_COMPILER=clang++-9 CXX=g++-8
      addons:
        apt:
          packages:
            - clang-9
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=g++-8 CODE_COVERAGE=true
      addons: { apt: { packages: ["g++-8", "libboost-test-dev"], sources: ["ubuntu-toolchain-r-test"] } }

before_script:
- |
  if [[ "${CODE_COVERAGE}" == "true" ]]; then
    CXX_FLAGS="-g --coverage"
    EXE_LINKER_FLAGS="--coverage"
  if
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_EXE_LINKER_FLAGS=${EXE_LINKER_FLAGS}

script:
- |
  cmake --build .
  ctest

after_success:
- |
  if [[ "${CODE_COVERAGE}" == "true" ]]; then
    sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
