os: linux
dist: trusty
language: cpp
compiler: 
- gcc
#- clang

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
#      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'   
    packages:
    - g++-7
#    - clang-5.0
    - libboost-test-dev

install:
- wget https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz
- tar xzvf cmake-3.8.2.tar.gz
- cd cmake-3.8.1/
- ./bootstrap
- make -j10
- sudo make install

before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script: 
- cd ${TRAVIS_BUILD_DIR}
- (mkdir build && cd build && cmake .. && make)
- ctest
