os: linux
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libboost-test-dev

install:
  - sudo update-alternatives --remove-all g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10

script: 
  - (mkdir build && cd build && cmake ..)
  - ctest
