language: cpp
os: linux
dist: bionic

matrix:
  include:
    - env: CXX_COMPILER=clang++-6.0 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-7 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - clang-7
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-8 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - clang-8
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-9 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - clang-9
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-10 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - clang-10
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-10 CXX_STDLIB=libc++
      addons:
        apt:
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=g++-7 CXX_STDLIB=g++-7 CODE_COVERAGE=true
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

    - env: CXX_COMPILER=g++-8 CXX_STDLIB=g++-8
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

    - env: CXX_COMPILER=g++-9 CXX_STDLIB=g++-9
      addons:
        apt:
          packages:
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

    - env: CXX_COMPILER=g++-10 CXX_STDLIB=g++-10

install:

################################################################################
# Third party dependencies are installed in ${TRAVIS_BUILD_DIR}/../third_party
################################################################################
- |
  THIRD_PARTY_DIR="${TRAVIS_BUILD_DIR}/../third_party"
  mkdir -p ${THIRD_PARTY_DIR}
  cd ${THIRD_PARTY_DIR}

################################################################################
# Install g++-10
################################################################################

- |
  if [[ "${CXX_COMPILER}" == "g++-10" ]]; then
    wget http://kayari.org/gcc-latest/gcc-latest.deb
    sudo dpkg -i gcc-latest.deb
    sudo ln -s /opt/gcc-latest/bin/gcc /usr/bin/gcc-10
    sudo ln -s /opt/gcc-latest/bin/g++ /usr/bin/g++-10
    sudo ldconfig /opt/gcc-latest/lib64
  fi

################################################################################
# Set gcc to latest version that is installed
################################################################################

- |
  if [[ "${CXX_STDLIB}" == "g++-7" ]]; then
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  elif [[ "${CXX_STDLIB}" == "g++-8" ]]; then
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  elif [[ "${CXX_STDLIB}" == "g++-9" ]]; then
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  elif [[ "${CXX_STDLIB}" == "g++-10" ]]; then
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
  fi
  gcc --version
  g++ --version

################################################################################
# Install the latest Boost and build Boost.Test (compiled with the latest gcc)
################################################################################
- |
  BOOST_VERSION=1.71.0
  BOOST_DIR=${THIRD_PARTY_DIR}/boost-${BOOST_VERSION}
  BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.bz2"
  BOOST_LIBS="test"
  BOOST_BUILD_TYPE="link=static variant=release"
  mkdir -p ${BOOST_DIR} && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xj -C ${BOOST_DIR}
  cd ${BOOST_DIR}
  if [[ "${CXX_STDLIB}" == "libc++" ]]; then
    sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-10
    ./bootstrap.sh --with-toolset=clang --with-libraries=${BOOST_LIBS}
    sudo ./b2 -d0 -j10 install toolset=clang ${BOOST_BUILD_TYPE} cxxflags="-stdlib=libc++"
  else
    ./bootstrap.sh --with-toolset=gcc   --with-libraries=${BOOST_LIBS}
    sudo ./b2 -d0 -j10 install toolset=gcc   ${BOOST_BUILD_TYPE}
  fi

################################################################################
# Install the latest CMake
################################################################################
- |
  CMAKE_VERSION=3.15.2
  CMAKE_DIR=${THIRD_PARTY_DIR}/cmake-${CMAKE_VERSION}
  CMAKE_URL="http://www.cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
  mkdir -p ${CMAKE_DIR} && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${CMAKE_DIR}
  export PATH=${CMAKE_DIR}/bin:${PATH}

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  if [[ "${CXX_STDLIB}" == "libc++" ]]; then
    cmake .. \
      -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
      -DCMAKE_CXX_FLAGS="-stdlib=libc++"
  elif [[ "${CODE_COVERAGE}" == "true" ]]; then
    cmake .. \
      -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
      -DCMAKE_CXX_FLAGS="--coverage" \
      -DCMAKE_EXE_LINKER_FLAGS="--coverage"
  else
    cmake .. \
      -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
  fi

script:
- |
  cmake --build .
  ctest

after_success:
- |
  if [[ "${CODE_COVERAGE}" == "true" ]]; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
