language: cpp
os: linux
dist: xenial

matrix:
  include:
    - env: CXX_COMPILER=clang++-6.0 CXX=g++-8
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-7 CXX=g++-8
      addons:
        apt:
          packages:
            - clang-7
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-8 CXX=g++-8
      addons:
        apt:
          packages:
            - clang-8
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=clang++-9 CXX=g++-8
      addons:
        apt:
          packages:
            - clang-9
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: CXX_COMPILER=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa
   
    # lcov on Ubuntu Xenial is incompatible with gcov-8, so we need g++-7 for code coverage
    - env: CXX_COMPILER=g++-7 CODE_COVERAGE=true
      addons:
        apt:
          packages:
            - g++-7
            - libboost-test-dev
          sources:
            - ubuntu-toolchain-r-ppa

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  if [[ "${CODE_COVERAGE}" == "true" ]]; then
    cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
  else
    cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
  fi

script:
- |
  cmake --build .
  ctest

after_success:
- |
  if [[ "${CODE_COVERAGE}" == "true" ]]; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
