os: linux
dist: trusty
language: cpp
compiler: 
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'   
    packages:
    - g++-7
    - clang-5.0
    - libboost-test-dev

install:

################################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

################################################################################
# Install the latest CMake
################################################################################
- |
  CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}ll
  cmake --version
 
before_script:
- |
  sudo update-alternatives --install /usr/bin/g++     g++     /usr/bin/g++-7       90
  sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-5.0 90
  g++ --version
  clang++ --version

script: 
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. 
  make
  ctest
