image:
  - Visual Studio 2017
 
environment:
    BOOST_ROOT: C:/Libraries/boost_1_66_0
    BOOST_LIBRARYDIR_WIN64: C:/Libraries/boost_1_66_0/lib64-msvc-14.1

configuration:
    - Debug
#    - Release

build:
    parallel: true

build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build     
    
    cd build    
    
    cmake .. -G "Visual Studio 15 Win64"        
    
    cmake --build .
    
test_script:
- cmd: ctest

